### ISSUE TITLE
Help with datafiles

### ISSUE THREAD

**Issue by fredrikw** [AmeresLab/UTRannotation#1]
Hi,

We have recently performed a QuantSec run on Rats and noticed several missed counts due to missing UTR annotations in the Rnor6.0 genome.
When discussing with Lexogen, they pointed us to this repository.
I have now tried to run the pipeline and after some tricks, I have come to the point that it is missing the files that contain Annotations (in nucleotideProfiles_markdown.new.Rmd lines 40-43). I understand that your files are for the human genome, but if you could give some tips on how to generate the files or what they contain it would be very helpful.

Kind regards,
Fredrik

**Comment by poojabhat1690** [comment]
Hello,

We had the same problem and decided to investigate this further for our QuantSeq data. I just pushed a folder that contains info about how to get the annotation that forms the basis to distinguish internal priming events. 

We also then used RNAseq to find the 'missing' annotations (this would be the next step of the pipeline).

Best,
Pooja

**Comment by fredrikw** [comment]
Many thanks for those files! It helped me move on. Now I have come to a different problem (or at least I think so, it might be something related to this one still). This time, the R code in overlappingHierarchical.R seems to be missing the functions `queryHits` and `subjectHits`. I think this is the reason why the call `refSeqOverlapping  = overlapAnnotations(peakFile = peaks_bedFile,annotation = utrAnnotation)` returns two empty arrays.

**Comment by poojabhat1690** [comment]
Is it possible that you do not have the R package GeomicRanges? The functions QueryHits and SubjectHits are from that package... could you please try this and let me know?

**Comment by fredrikw** [comment]
Yes, I noticed that this might not be the problem. I'm investigating more...

**Comment by fredrikw** [comment]
I'm back...
The last problem was due to a mismatch in chromosome naming between my reads and the reference sequence.
I have now been able to move on a bit after a few fixes (will submit a PR when I have everything working).
But, now it bails out when trying to plot nucleotide profiles.
I'm running with a limited set of reads to speed up during testing. This results in "PASfractions" where some categories are empty. (e.g. ensembl_divided contains sequences in only 7 of the categories.) And especially after splitting into PAS/noPAS there is a lot missing.
This in turn leads to categories being dropped at line 199-200 of nucleotideProfiles_markdown.new.Rmd
(By the way, shouldn't the "1" at line 196 be a "0"?)
And when categories are dropped, in my case for ensembl but not for refSeq, the loop at 226 will error out with `subscript out of bounds`.
I don't understand the code well enough to say what is the biggest problem here, but why are empty categories dropped?

**Comment by fredrikw** [comment]
Next question...
In `addingIntergenicPeaks.R`, line 35 `bedtools` is called on files in `"BIn"/rnaseq/*_single.Aligned.sortedByCoord.out.bam`. What do these files contain? And how are they created?

**Comment by poojabhat1690** [comment]
Hi sorry for the delay in replying.. did you already get through the nucleotide profiles? (if not i will get back to you a bit later)

the Bam file contains mapped RNAseq data..mapped with STAR aligner.. we used these to look for downstream 'un-annotated mRNA 3' ends', this would probably be the most crucial step for you if you have missing 3' UTRs in the annotations...I should also get to a more comprehensive documentation soon!

**Comment by fredrikw** [comment]
Ok, great! I have those files as well...

I got through the nucleotide profiles by skipping the removal of empty categories at `nucleotideProfiles_markdown.new.Rmd` lines 199-200. It looks like that didn't hurt the following analysis.

**Comment by poojabhat1690** [comment]
Great! I hope this solves your issues of missing annotations!

**Comment by poojabhat1690** [comment]
Make sure to have the correct strandedness while using bedtools...

**Comment by fredrikw** [comment]
Thank you very much for your continued help!

I don't completely understand your latest comment, and I think it is involved in my current obstacle. If I run `addingIntergenicPeaks.R` as it is in the repository (with `bamtools multicov -S`) I get an empty `allIntergenicPeaks_n100_new.txt`. If I instead try with `bamtools multicov -s` I get results in the "allIntergenicPeaks-file".

How do I know which version I should use for my data? Is there a good way to find out or should I just go with the one that gave results? I'm new to this kind of analysis, so I don't really know the theory well enough to answer the question myself...

Another (final?) question. In `mergingCounting.new.R` you add data from `pri_miRNAloci.txt`. What is that file and do I need to add those data and how will I create such a file in that case?

**Comment by poojabhat1690** [comment]
Hello, 

Sorry for the delay in getting back to you. I have been out of office. 

The -S on the bedtools multicov is used to count reads on the opposite strand. In our case the library prep and mapping was such that genes on the positive strand showed signal on the negative strand (this could be changed at the mapping stage). To inspect this, i would just load the bam files on IGV and see if your reads are on the opposite strand than you would expect. 

Also we wanted to use pri-mirna loci as they are also polyadenylated and should be captured by quantSeq. We manually annotated these pri-miRNA (looking at mature miRNA loci, 5' end sequencing and 3' end sequencing). Depends if you are interested in this...

**Comment by fredrikw** [comment]
No problem! I was away myself for a while.

I encountered one more problem regarding refFlat files. There are two different refFlat-files used in the pipeline. In `getAnnotations.Rmd` the file `"ucscDir"/refSeq_refFlat_utrAnnotations` is used while in `getLongestUTR.Rmd` and `mergingCounting.new.R` the file loaded is `"ucscDir"/refFlat.txt`. The former one seems to be the one that most resemble the instructions in `gettingAnnotations.txt` and that is the file I have used so far. However, that file (which is a bed-file according to the instructions) does not match the code in at least `mergingCounting.new.R` so I suppose that you have a different file as well... Could it be that `refFlat.txt` is a straight export of the refFlat table from Genome Browser?

I tried with a straight export like above and it seems to have worked in that I could now run through the entire pipeline. But, now I don't really understand the results. I was hoping for some overview of the data showing potential missed UTRs and possibly an updated annotation file or something. Is it `ends_greater90percent_intergenic_n100.bed/txt` that contain the final annotations? In that case, how do you use the counts from the file? Is it the number of reads that are within the "new" UTR?

**Comment by poojabhat1690** [comment]
Hello,

Yes, the refFlat is downloaded from the UCSC genome browser. 

Also, the bed file 'ends_greater90percent_intergenic_n100.bed' gives you the list of the 'high confidence mRNA 3' ends' that are expressed in the sample. From each of these high confidence ends we create 250 nt windws as  QuantSeq reads map on average to the last 250nts of the mRNA 3' ends. In addition to this, we also do not want to miss out 3' ends that are actually present in the transcriptome (which are present in the annotation but not captured by the quantSeq data), so we add back the 250nts of refSeq 3' UTR annotations. And since we cannot distinguish transcripts that are <250nts away from each other, we collapse them --> and count quantSeq reads in these regions... this will already be in the bed file - > allAnnotations.bed. 

You would have to use these annotations to further count the reads in these annotations.
